APPOTHER = cpuinfo sprinit0 sprinit_raw
include Makefile.common

cpuinfo: cpuinfo.o cpuinfo-z80.o
	$(LINKER) -o $@ $(LINKER_OPT) $(CRT0) $^ $(LINKER_TAIL)

sprinit_raw: sprinit_raw.s
	rm -f sprinit_raw.rel sprinit_raw.ihx sprinit_raw.lk sprinit_raw.lst sprinit_raw.sym sprinit_raw.noi sprinit_raw
	sdasz80 -o sprinit_raw.rel sprinit_raw.s
	sdldz80 -b _HEADER=0x0100 -n -i sprinit_raw.ihx -m -j sprinit_raw.rel
	makebin -p -o 0x100 sprinit_raw.ihx sprinit_raw

sprinit0:
	@:

sprinit0.o:
	@:
